services:
  - type: web
    name: rose-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    pythonVersion: 3.10.13
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: HF_MODEL_REPO
        value: AnnaPakir/diffusion-bot

